hydra:
  run:
    dir: /dev/null #outputsが出力されないようにする
  sweep:
    dir: /dev/null #パラメータスイープ時もoutputsが出力されないようにする

mlflow:
  enable: True
  experiment_name: Default
  tracking_dir: results/mlruns # run_experiments.pyからの相対パスを書く

save_dir:
  mlflow: # tracking_dirからの相対パスを書く
    config: "" # ファイル名はlocalの名前が使用されるため記述不要 
    best_model: "" # 同上
  local: # run_experiments.pyからの相対パスを書く
    config: results/output/config.yaml
    best_model: results/output/best_model.pth

dataset:
  subset_size_ratio: 0.1
  train_size_ratio: 0.7

train_param:
  num_epochs: 5
  batch_size: 8
  learning_rate: 0.001

test_param:
  batch_size: 8