hydra:
  run:
    dir: "" #outputsが出力されないようにする
  sweep:
    dir: "" #パラメータスイープ時もoutputsが出力されないようにする

mlflow:
  enable: True
  experiment_name: "Default"
  tracking_dir: "results/mlruns" # run_experiments.pyからの相対パスを書く
  write_loc: # tracking_dirからの相対パスを書く（ファイル名は不要）
    config: ""  
    best_model: ""

local:
  read_loc:
    rawdata_dir: "./data/raw"
  write_loc:
    config: "results/output/config.yaml"
    best_model: "results/output/best_model.pth"

hparam:
  num_epochs: 2
  train_batch_size: 8
  val_batch_size: 8
  learning_rate: 0.001
  test_batch_size: 8